version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels: [dependencies, ci]
    groups:
      actions:
        patterns: ["*"]
    open-pull-requests-limit: 5

  - package-ecosystem: uv
    directory: /
    schedule:
      interval: weekly
    labels: [dependencies]
    groups:
      python-dependencies:
        patterns: ["*"]
    open-pull-requests-limit: 5

  - package-ecosystem: gitsubmodule
    directory: /
    schedule:
      interval: weekly
    labels: [dependencies, packaging]
